export const siteConfig = {
  name: "TradeInsight",
  description: "The world's most advanced trading journal. Track trades, analyze performance, and master your strategy with AI-powered insights.",
  url: "https://tradeinsight.io",
  paymentLink: "https://tradeinsight.readyfoodbd.shop/step/store-checkout-04/",
  telegramUrl: "https://t.me/tradeinsightbd",
  supportEmail: "theiraffx@gmail.com",
  whatsappNumber: "8801403741183",
  officeLocation: "Dhaka, Bangladesh",
};

export const pricingPlans = [
  {
    id: "starter",
    name: { en: "Starter", bn: "স্টার্টার" },
    target: { en: "Beginner Traders", bn: "নতুন ট্রেডার" },
    price: 5,
    priceBDT: 500,
    period: "/month",
    popular: false,
    features: [
      { text: { en: "Trading Journal", bn: "ট্রেডিং জার্নাল" }, included: true },
      { text: { en: "Trade History", bn: "ট্রেড ইতিহাস" }, included: true },
      { text: { en: "Basic Analytics", bn: "বেসিক অ্যানালিটিক্স" }, included: true },
      { text: { en: "Manual Trade Entry", bn: "ম্যানুয়াল ট্রেড এন্ট্রি" }, included: true },
      { text: { en: "Screenshot Upload", bn: "স্ক্রিনশট আপলোড" }, included: true },
      { text: { en: "Performance Tracking", bn: "পারফরম্যান্স ট্র্যাকিং" }, included: true },
      { text: { en: "Basic Support", bn: "বেসিক সাপোর্ট" }, included: true },
      { text: { en: "Advanced Analytics", bn: "উন্নত অ্যানালিটিক্স" }, included: false },
      { text: { en: "AI Insights", bn: "AI ইনসাইটস" }, included: false },
      { text: { en: "Risk Management Tools", bn: "ঝুঁকি ব্যবস্থাপনা টুলস" }, included: false },
    ],
    cta: { en: "Start Trading", bn: "ট্রেডিং শুরু করুন" },
    buyLink: "https://tradeinsight.readyfoodbd.shop/step/store-checkout-04/",
  },
  {
    id: "pro",
    name: { en: "Pro", bn: "প্রো" },
    target: { en: "Serious Traders", bn: "সিরিয়াস ট্রেডার" },
    price: 10,
    priceBDT: 1000,
    period: "/month",
    popular: true,
    features: [
      { text: { en: "Everything in Starter", bn: "স্টার্টারের সব ফিচার" }, included: true },
      { text: { en: "Advanced Analytics", bn: "উন্নত অ্যানালিটিক্স" }, included: true },
      { text: { en: "Unlimited Trade Entries", bn: "অসীম ট্রেড এন্ট্রি" }, included: true },
      { text: { en: "Advanced Trading Dashboard", bn: "উন্নত ট্রেডিং ড্যাশবোর্ড" }, included: true },
      { text: { en: "Risk Management Tools", bn: "ঝুঁকি ব্যবস্থাপনা টুলস" }, included: true },
      { text: { en: "Trading Psychology Notes", bn: "ট্রেডিং সাইকোলজি নোটস" }, included: true },
      { text: { en: "Second Account Support", bn: "দ্বিতীয় অ্যাকাউন্ট সাপোর্ট" }, included: true },
      { text: { en: "Multiple Trading Account Tracking", bn: "একাধিক ট্রেডিং অ্যাকাউন্ট ট্র্যাকিং" }, included: true },
      { text: { en: "Monthly Performance Report", bn: "মাসিক পারফরম্যান্স রিপোর্ট" }, included: true },
      { text: { en: "Priority Support", bn: "প্রায়োরিটি সাপোর্ট" }, included: true },
    ],
    cta: { en: "Upgrade to Pro", bn: "প্রোতে আপগ্রেড করুন" },
    buyLink: "https://tradeinsight.readyfoodbd.shop/step/store-checkout-04-2/",
  },
  {
    id: "elite",
    name: { en: "Elite", bn: "এলিট" },
    target: { en: "Professional Traders", bn: "পেশাদার ট্রেডার" },
    price: 15,
    priceBDT: 1500,
    period: "/month",
    popular: false,
    features: [
      { text: { en: "Everything in Pro", bn: "প্রোর সব ফিচার" }, included: true },
      { text: { en: "AI-Powered Trade Insights", bn: "AI-চালিত ট্রেড ইনসাইটস" }, included: true },
      { text: { en: "Strategy Backtesting", bn: "স্ট্র্যাটেজি ব্যাকটেস্টিং" }, included: true },
      { text: { en: "Trade Replay", bn: "ট্রেড রিপ্লে" }, included: true },
      { text: { en: "Unlimited Accounts", bn: "অসীম অ্যাকাউন্ট" }, included: true },
      { text: { en: "Team Collaboration", bn: "টিম কোলাবোরেশন" }, included: true },
      { text: { en: "Custom Report Builder", bn: "কাস্টম রিপোর্ট বিল্ডার" }, included: true },
      { text: { en: "API Access", bn: "API অ্যাক্সেস" }, included: true },
      { text: { en: "White-Label Reports", bn: "হোয়াইট-লেবেল রিপোর্ট" }, included: true },
      { text: { en: "Dedicated Account Manager", bn: "ডেডিকেটেড অ্যাকাউন্ট ম্যানেজার" }, included: true },
    ],
    cta: { en: "Go Elite", bn: "এলিটে যান" },
    buyLink: "https://tradeinsight.readyfoodbd.shop/step/store-checkout-04-2-2/",
  },
];
